---
development:
  # Infrastructure
  APP_HOST: http://localhost:9292
  API_HOST: https://thsr-parking-api.herokuapp.com

test:
  # Infrastructure
  APP_HOST: http://localhost:9292
  API_HOST: http://localhost:9090

app_test:
  # Application
  APP_HOST: http://localhost:9292
  API_HOST: http://localhost:9090

production:
  # Infrastructure
  API_HOST: https://thsr-parking-api.herokuapp.com